version: "3.9"

services:
  postgre_personal_project:
    container_name: postgre_personal_project
    image: codydale1/postgre_personal_project:1.0.0
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
  
  db:
    container_name: db
    image: postgres:12
    ports:
      - ":5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: psql_personal_project
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}
    